### PR TITLE
chore: use @babel/eslint-parser

### PR DESCRIPTION
**Pull request by domoritz**
Use babel eslint parser since it always supports the latest js features. 

Alternatively, we can use https://github.com/vega/vega/pull/3098 if we only want to support e.g. nullish coalescing.

### CODE REVIEW

**Comment by jheer** [comment]
This looks fine, but can you include a short note about the reason for switching to this parser?

**Comment by jheer** [comment]
If this is related to #3096 and support for `??`, I'm a bit skeptical (more regarding #3096 than this particular PR). I believe Node 12 does not support the `??` operator but is still used in production in various companies, etc. We will need to test and make sure the build + babel outputs are correct and working for older but still relatively modern runtimes.

**Comment by domoritz** [comment]
I added a note to the pull request. Yes, this is to support any JavaScript features babel supports. Since all packages run through Babel, I think we should be able to use `??` or any other modern js features. We should still confirm that it's working correctly, though.

**Comment by domoritz** [comment]
I believe that https://github.com/vega/vega/pull/2908 is necessary to ensure everything we publish runs through babel.

**Pull request merged**
