### PR TITLE
feat: add typing to label-transform properties

### PR DESCRIPTION
**Pull request by chanwutk**

### CODE REVIEW

**Review by domoritz — APPROVED** [review]
Looks good but tests are failing

**Comment by chanwutk** [comment]
It seems like the failing tests are the same ones from #3124. Should I try to fix it here, or should I wait for fixes in #3124 and rebase?

**Comment by domoritz** [comment]
Ahh, right. No, it should be fixed in https://github.com/vega/vega/pull/3124

**Comment by domoritz** [comment]
These changes will make it easier for us to import the types in https://github.com/vega/vega-lite/pull/7222.

**Pull request merged**
