### PR TITLE
[WIP] Add data-driven options support for bind.

### PR DESCRIPTION
**Pull request by aodhan-domhnaill**
Works with test spec for select.

Still needs,
* Unit tests
* Radio buttons support

### CODE REVIEW

**Comment by aidan-plenert-macdonald** [comment]
Looks like a Scenegraph is failing. I'm not sure how those are generated

**Comment by domoritz** [comment]
Here: https://github.com/vega/vega/blob/233f714f65e3624e8fd73c1aaa6ee86aa1c2a9ac/packages/vega/test/scene-test.js#L1

**Comment by jheer** [comment]
Pertains to #778.

Thanks for working on this! A few notes for refining the contribution:

- Be sure propose and discuss specification syntax additions within the relevant GitHub issue (here, #778)
- Please use modular PRs. Break up changes into multiple PRs where sensible. For example, separating changes to vega-loader from changes to vega-view.
- Do not include build file changes in PRs (e.g., don't include vega.js, docs/vega.js, etc.)
- Do not bump version numbers of packages. Instead, document changes to packages in PR comments, including whether you think the PR makes major, minor, or patch-level changes.

**Comment by aidan-plenert-macdonald** [comment]
@jheer Hey, I was a little lazy to break the stuff up, but I did it. Couple questions

> Be sure propose and discuss specification syntax additions within the relevant GitHub issue (here, #778)

I put a comment about the syntax change in the issue a while back, but never got feedback. It was a relatively simple minor change and fit with syntax in other places.

> Please use modular PRs. Break up changes into multiple PRs where sensible. For example, separating changes to vega-loader from changes to vega-view.

I broke the commit up by submodule, but they interact between modules. Do you want me to have multiple PR's still? The tests won't pass until all the code changes get merged.

> Do not include build file changes in PRs (e.g., don't include vega.js, docs/vega.js, etc.)

I dropped this commit

> Do not bump version numbers of packages. Instead, document changes to packages in PR comments, including whether you think the PR makes major, minor, or patch-level changes.

I guess someone else's commits got mixed in so I removed them. Should be good now.

**Comment by danmarshall** [comment]
Hello @aidan-plenert-macdonald, FYI a new `labels` array property has been added which allows overriding the display text of options. #2152 #2158 Might make sense to add labels in this PR.

**Comment by thegasta** [comment]
Any updates on this?

**Comment by seingierf** [comment]
Hi!
Any chance this PR could be reconsidered?
I'm trying to automatically populate the input selection options for system metrics visualization in Kibana (per-something activity: network, disk, process, etc...)
This is probably one among many other examples in which building input labels from the dataset would be extremely useful.
Thanks!

**Comment by stoerr** [comment]
Yes, pleeease! We have a couple of drop downs that influence the diagram and have dynamic values. It seems the only way to do something like that right now would be an external option, right? And how about multiple selects?

**Pull request closed without merging**
