### PR TITLE
Packed Bubble Chart Example

### PR DESCRIPTION
**Pull request by PBI-David**
@domoritz adding a packed bubble chart example. I think I have added the required files in the right places but this is my first time contributing and using GitHub so apologies in advance if I haven't got it completely right.

### CODE REVIEW

**Comment by jheer** [comment]
Thanks @PBI-David! Retargetting PR to `v5.22.0` branch for staging prior to next release.

**Comment by PBI-David** [comment]
@jheer I just checked the new release and FYI when clicking the link for "View in Online Vega Editor" [here](https://vega.github.io/vega/examples/packed-bubble-chart/), there seems to be a problem loading the spec. Apologies if I missed something.

**Comment by domoritz** [comment]
Yes, instead of sending the spec, for examples we just refer to the example by id. This means we need to update the Vega package in the editor.

**Comment by domoritz** [comment]
Done. See https://vega.github.io/editor/#/examples/vega/packed-bubble-chart.

**Pull request merged**
