### PR TITLE
Build tests before testing typings.

### PR DESCRIPTION
**Pull request by domoritz**
I think this could be a good way to ensure that the typings stay up to date.

### CODE REVIEW

**Comment by domoritz** [comment]
Related: https://github.com/vega/vega/pull/1551

**Comment by jheer** [comment]
Why are builds failing for this and #1551? I don't really understand what is going on here as I have not been involved with the vega-typings package, and I don't want to merge anything until I have a better sense of what is failing here. Explanations welcomed! :)

**Comment by domoritz** [comment]
It's failing because the typings are not up to date with the examples.

This PR only enables additional tests to show that the typings are not up to date and provides a way to test typings against the examples automatically. What the tests do is generate a JS version of the examples and test whether they are valid according to the typings we have for Vega specs. The tests will pass again once the typings have been updated.

**Comment by jheer** [comment]
I see. So to resolve we need to update the typings to reflect the changes that have been made to the vega schema?

**Comment by domoritz** [comment]
Yes. At the very least, we need to update the typings to reflect the changes in the examples.

**Comment by domoritz** [comment]
Part of #1551

**Pull request closed without merging**
