### PR TITLE
Add geoScale vega function to support altair_tiles

### LINKED ISSUE #3758: Support accessing projection scale function in top-level scope for (geo)-tiles integration
Context: In the package [altair_tiles](https://github.com/altair-viz/altair_tiles) we are exploring how we can include (geo)tile-layers, such as openstreetmap basemaps, within Altair. 
Currently this is possible if there is a `projection-scale` set upfront in the specification. 

But a more common case within the context of Vega-Lite is to use a `projection-fit` object. 
One of the question now is*, how to get the `projection-scale` value if this scale is internally derived within the projection? And especially, how to get this scale value as parameter/signal using Vega Expressions? 

An example:
Given the following Vega-Lite specification [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAdxoATemgDMABh1L4NMlm16lapJhSpQDAE6C0IC1YLK2DtfwCM3nQikZeSUAMw9kTDRQTABPHDgnTDYcNmk5RRAQuEt7BPQoNgZZTDsaOAgQAF9KpRw7VLgoTHZ5G0y6KJBY+KcAMWzMXIyyODYEOBKYzu68kAAFNkEYsnSlAo81GllLcrQAbQOxbwUtAHYAXQU9o4V+LQAWS72fU9uHp5eTi6ubs-P-mogOrJOB2Zq7GzVJQzJzjOxQSweKq1JB2JAICqoPagbbjJwAWQAmgB9OYAJQA8gApDJwAAedScBRwMQAFAByYGSRrNOTsgCUVUuIGQdgA1tM4rMRmwIDAkD1QjRBI50MJjJgyGipkoICU2GLpdqMlBhDg0CUGHBqkA):
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "width": 300,
  "height": 300,
  "data": {
    "url": "data/world-110m.json",
    "format": {"type": "topojson", "feature": "countries"}
  },
  "projection": {
    "fit": {
      "type": "Feature",
      "geometry": {
        "type": "Polygon",
        "coordinates": [[[51, 37], [51, -34], [-17, -34], [-17, 37], [51, 37]]]
      },
      "properties": {}
    },
    "type": "mercator"
  },
  "params": [{"name": "MY_PROJ", "expr": "copy('projection')"}],
  "mark": {
    "type": "geoshape",
    "fill": "lightgray",
    "stroke": "gray",
    "clip": true
  }
}
```

We can get the `'projection'` as signal value using:
```json
{"name": "MY_PROJ", "expr": "copy('projection')"}
```
That will be shown as such in the Signal viewer:
| Signal  | Value                                        |
|---------|----------------------------------------------|
| MY_PROJ | function W(e){return C(e[0]*l.uR,e[1]*l.uR)} |

Within the developer tools I now can do:
```js
VEGA_DEBUG.view.signal('MY_PROJ').scale()
```
And this will return the `scale` value derived internally.
```js
192.4605326941414
```

And it is exactly that value that we need within the specification for correct tile support (see this example with an openstreetmap tile layer using `fit`: [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgFgpglg5mAuIBcBmADGgNCA7lAJvGMuliADYCGAnhAE7IDao+l8lyoAzhAI4CuEAHYBjCJxBd2dREjJSA9gAdkARjKUuyEBwC+2IZQC24pCHhRyEAPrkoUkPpBHKdANYT41JaZBQXMOLYInYqSPB0gtiQsAgSEAAeSgxmFlbWXFAAXhAABADUuaqO2HiExEigicnaaTaZOQVFjk7CIgr4UEIwEvx05BIAZlAQ5PjafQPYXj7aQgpGXZQDTglDI2Paa9hcIsumQvzk5NPevgKUQhbsFgBu4k7U66PjZk87e1bIh8ens2YXK5QG5Qe4tbDJBQAKwgIgsCiEEjEV3oTCwAFY0ABdbB0BQ3UyMAC06kwWGxH32yAALBg-r4THQ9vAFAwnBFLlxBqyjExQJ8REc2L4eAI2hAABRYIpoACUIGwmm0ACMSqBBlR4PBhEwQKqsfp+ctBZrfAByBDwJRcJAAeltdQAdMphFI6BAIPAXEpnXQYLazU0sgoFtYxJYmmaA00JRLWPB+EZHZQmp0oNYNSG6E06lwwwp+FdZbkAKS5XP5wvwYuFKOBwpxtiJx3K1NQqEZ8hZmu5M2OpTdM0KnRaMyTNUgAVC7XaePNlMAKnLlnq2TyhXwCRjdQya9yttyACZ5YrRyA1obJ8bp7450nW0udw117l8NRtyvd40D8fh0q3o4BqYCwbAcJUIDjmYlrWnatoiPgQiOlCXD4KMoJ0I6QieraQhKEYtr3DAlBEvGmielwAACtyqI6h4AJyOmgtqkbaOCsmMJLqEmyEIsO3J0C4sjqhATbuto7RVnQIxaPStTKNCXC8boTguO4nhnNogQKFwYCULM2DDMcADySiUCIwJPHIjqqDsEQKG4vispcgTDm69kQAA6gQRDIIewShMgESCK0ogdF0PTgYZAyRRsrx+OM2BWIEQivD8JzmBpAL8Jc1xsKCDxOJCMJwlAvExUJGX-CAABiIkJmJ2BaSYESWaAMy+AACgo5DUDAvHBFmnSGNqo6MGN6I2SgADsOKMBNmBEig1KzSSU0LUtK2qGt02zfNO1YkBICQj4MjSZwymyWYjLMqyLQ4kdrjGKNoCGCY2gALIAJrWB1ABKRkAFLDtUKSTso1ASmaRWwvCQhmvKl6vb4X3WAAygAwgAggAMgAosDSSg6odGHo61IAGxoOiKCHuTdHUqoDPUhOSMqmR1hPmuBM1GYEqHrkS4dQAkgLuQoxjOO48WB5KAoOB85guTBqGVj3OQCPASArNmMrRi2BAavDrcyyCL5iPGL4uthtAUwgCD4k2xKVuq6MGsvRbtQrnmElXNzoOy-LflKyGevhurLMe6kn7Pn7bM8Bz0d7kuAcK8HKsG6MuREmnoc227WuR3q7Oy10iDYPbZhdPcMiQ9DJUImaiuMNK2L59rIBprHvPKsXCil83WJNKoAAccr7rkKCU6LFY+4g5tvWYaadlmXcgJmrJxlAUBt4Xm6r5v6br9m2dpsWj6JzkEcLx37b76oWe5F2MASuwQgSj38cl1cjCqIPgsiweEeY9Cj3wPO0Lg79e791-qLYW48gGymlrkYWSD+bnysN7Asvt563nbMvW65dCbaCPnGdsO9r5vlXniQs+BYz4DwUfB+9CoRn2XOkZ8CN7oABJdiQBcNoaCNp7SEUoI6GAwIwD8GVI6UqtpeEQBcARCAREiR2G1ARdEjph6MSQopRE2BSI8HgKOKoRglBeD5LoA0uggA)).

If I try :
```json
"params": [
    {"name": "MY_PROJ", "expr": "copy('projection')"},
    {"name": "MY_SCALE", "expr": "MY_PROJ.scale()"}
],
```
I get the following error [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAdxoATemgDMABh1L4NMlm16lapJhSpQDAE6C0IC1YLK2DtfwCM3nQikZeSUAMw9kTDRQTABPHDgnTDYcNmk5RRAQuEt7BPQoNgZZTDsaOAgQAF9KpRw7VLgoTHZ5G0y6KJBY+KcAMWzMXIyyODYEOBKYzu68kAAFNkEYsnSlAo81GllLcrQAbQOxbwUtAHYAXQU9o4V+LQAWS72fU9uHp5eTi6ubs-P-mogOrJOB2Zq7GzVJQzJzjOxQSweKq1JB2JAICqoPagbbjJwAWQAmgB9OYAJQA8gApDJwAAedScBRwMQAFAByYGSRrNOTsgCUyJx6NmROJAGUAMIAQQAMgBRWkMuwEknk6mUaBIQRwVmCyqXEDIOwAa2mcVmIzYEBgSB6oRogkc6GExkwZDRUyUEBKbBNls9GSgwhwaBKDDg1SAA):
```cmd
[Error] Illegal callee type: MemberExpression
```

And upon reading the [Vega Expressions](https://vega.github.io/vega/docs/expressions/) documentation page (continuously a joy to read) I notice the following sentence:

> In addition, function calls involving nested properties (`foo.bar()`) are not allowed. Instead, the expression language supports a collection of functions defined in the top-level scope.

So I finish this issue with a feature request to support the access of the projection-scale function in the top-level scope. 
I'm aware that there already exist a scale function. So it probably needs to named differently.

\* Cross-referencing the corresponding altair_tiles [issue](https://github.com/altair-viz/altair_tiles/issues/3)

### PR DESCRIPTION
**Pull request by binste**
In [altair_tiles](https://github.com/altair-viz/altair_tiles) we are exploring how we can include (geo)tile-layers, such as openstreetmap basemaps, within Altair. The development is progressing well and the biggest road block we have so far is that we cannot access the `scale` value of a geo projection. Closes #3758 <- This issue explains why we need this and contains some example specs (cc @mattijn).

This PR introduces a `geoScale` vega function which fetches the named projection and calls `.scale()` on it. I named it `geoScale` to differentiate from the existing `scale` function.

I added a spec to the `test` folder which showcases how it can be used. This is somewhat the spec that we will produce with `altair_tiles` (run `yarn serve` to see it):

image

This is the first time I'm working on Vega so it's likely that I missed something. Happy to work more on this and push it over the finish line with some guidance.

### CODE REVIEW

**Comment by jheer** [comment]
Thanks! This looks good, except that none of the docs build files should be included in the PR. Can you please first remove the files under `docs` (except for `docs/docs/expressions.md`), such as `docs/vega-core.js`, etc.?

**Comment by binste** [comment]
Thank you for the review! I reverted all changes to the docs files except for `docs/docs/expressions.md`.

**Comment by binste** [comment]
I added the missing scenegraph file in `vega` and spec file in `vega-typings` (3718d1f788a0d5f81704eb43820492b00da549de). All tests now pass locally.

**Comment by binste** [comment]
Very gentle ping. This is the missing piece to make altair_tiles work and after which we could release a first version of it. Just want to make sure the PR doesn't fall through the cracks but of course totally understand if your busy with other things/on vacation/... :)

**Pull request merged**
