### PR TITLE
fix: add missing color schemes

### PR DESCRIPTION
**Pull request by marcprux**
**vega-typings**
* add missing color schemes

The schemes that are new as of vega5 (https://vega.github.io/vega/docs/schemes/) were missing from the typing.

### CODE REVIEW

**Comment by domoritz** [comment]
Thank you! Can you format the code with prettier?

**Comment by domoritz** [comment]
We use a particular prettier config. I'll format the code.

**Comment by domoritz** [comment]
Replaced by https://github.com/vega/vega/pull/2631

**Comment by marcprux** [comment]
Sorry about that. Is the correct procedure to run the `format` script in `vega-typings/package.json`?

**Pull request closed without merging**
