### PR TITLE
Use config type in spec.

### PR DESCRIPTION
**Pull request by domoritz**
Replaces https://github.com/vega/vega/pull/1933

### CODE REVIEW

**Comment by danmarshall** [comment]
Travis seems stuck.

**Comment by domoritz** [comment]
It's really slow because we use mac os instead of linux.

**Comment by domoritz** [comment]
Ohhh

```
npm WARN lifecycle The node binary used for scripts is /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/yarn--1566251071943-0.01913260304278208/node but npm is using /Users/travis/.nvm/versions/node/v8.16.1/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
Error: /Users/travis/build/vega/vega/packages/vega-typings/tests/spec/valid/layout-splom.ts:6:3
ERROR: 6:3   expect  TypeScript@next compile error: 
Type '{ "axis": { "tickColor": string; "domainColor": string; }; "legend": { "layout": { "anchor": { "signal": string; }; }; }; }' is not assignable to type 'Config'.
  Types of property 'legend' are incompatible.
    Type '{ "layout": { "anchor": { "signal": string; }; }; }' is not assignable to type 'LegendConfig<NumberValue, number | SignalRef, StringValue, ColorValue, FontWeightValue, StringValue, AlignValue, TextBaselineValue, "all" | "none" | SignalRef | "each", ... 5 more ..., "left" | ... 8 more ... | "bottom-right">'.
      Types of property 'layout' are incompatible.
        Type '{ "anchor": { "signal": string; }; }' is not assignable to type 'LegendLayout'.
          Types of property 'anchor' are incompatible.
            Type '{ "signal": string; }' is not assignable to type '"start" | "end" | "middle" | null | undefined'.
              Type '{ "signal": string; }' is not assignable to type '"middle"'.
/Users/travis/build/vega/vega/packages/vega-typings/tests/spec/valid/legends-discrete.ts:12:7
ERROR: 12:7  expect  TypeScript@next compile error: 
Type '{ "legend": { "offset": number; "gradientDirection": "horizontal"; "gradientLength": number; "gradientWidth": number; }; }' is not assignable to type 'Config'.
  Types of property 'legend' are incompatible.
    Type '{ "offset": number; "gradientDirection": "horizontal"; "gradientLength": number; "gradientWidth": number; }' is not assignable to type 'LegendConfig<NumberValue, number | SignalRef, StringValue, ColorValue, FontWeightValue, StringValue, AlignValue, TextBaselineValue, "all" | "none" | SignalRef | "each", ... 5 more ..., "left" | ... 8 more ... | "bottom-right">'.
      Object literal may only specify known properties, and '"gradientWidth"' does not exist in type 'LegendConfig<NumberValue, number | SignalRef, StringValue, ColorValue, FontWeightValue, StringValue, AlignValue, TextBaselineValue, "all" | "none" | SignalRef | "each", ... 5 more ..., "left" | ... 8 more ... | "bottom-right">'.
/Users/travis/build/vega/vega/packages/vega-typings/tests/spec/valid/scatter-plot.ts:10:3
ERROR: 10:3  expect  TypeScript@next compile error: 
Type '{ "legend": { "titleOrient": "left"; "offset": number; "symbolDirection": "horizontal"; "symbolFillColor": string; "symbolStrokeWidth": number; "symbolOpacity": number; "symbolType": string; "layout": { "right": { ...; }; "bottom": { ...; }; "top": { ...; }; }; }; }' is not assignable to type 'Config'.
  Types of property 'legend' are incompatible.
    Type '{ "titleOrient": "left"; "offset": number; "symbolDirection": "horizontal"; "symbolFillColor": string; "symbolStrokeWidth": number; "symbolOpacity": number; "symbolType": string; "layout": { "right": { "direction": "vertical"; "anchor": { ...; }; }; "bottom": { ...; }; "top": { ...; }; }; }' is not assignable to type 'LegendConfig<NumberValue, number | SignalRef, StringValue, ColorValue, FontWeightValue, StringValue, AlignValue, TextBaselineValue, "all" | "none" | SignalRef | "each", ... 5 more ..., "left" | ... 8 more ... | "bottom-right">'.
      Types of property 'layout' are incompatible.
        Type '{ "right": { "direction": "vertical"; "anchor": { "signal": string; }; }; "bottom": { "margin": number; "direction": "vertical"; "anchor": "middle"; "center": true; }; "top": { "margin": number; "direction": "vertical"; "anchor": "end"; }; }' is not assignable to type 'LegendLayout'.
          Types of property 'right' are incompatible.
            Type '{ "direction": "vertical"; "anchor": { "signal": string; }; }' is not assignable to type 'BaseLegendLayout<number | SignalRef, boolean | SignalRef, SignalRef | "horizontal" | "vertical", LayoutBounds, TitleAnchor>'.
              Types of property 'anchor' are incompatible.
                Type '{ "signal": string; }' is not assignable to type '"start" | "end" | "middle" | null | undefined'.
                  Type '{ "signal": string; }' is not assignable to type '"middle"'.
```

**Comment by jheer** [comment]
LGTM. Tests are passing now. @domoritz, is this ready to merge?

**Comment by domoritz** [comment]
Yes. Note that I updated one spec: https://github.com/vega/vega/pull/1934/files#diff-dd8c690ee371060287288ff2997a9358L10.

**Pull request merged**
