### PR TITLE
Logger docs and typings corrections

### PR DESCRIPTION
**Pull request by domoritz**
Fixes https://github.com/vega/vega/issues/2660

### CODE REVIEW

**Comment by jheer** [comment]
Thanks! LGTM, except (a) the logger and logLevel method descriptions appear to be mismatched and (b) I think we’re still missing docs for the logger View constructor option.

Also, let’s target this into the v5.13.0 branch.

**Comment by domoritz** [comment]
Okay. Do you want me to combine this pull request with https://github.com/vega/vega/pull/2661 or can you merge it separately?

**Comment by domoritz** [comment]
I fixed the mismatched docs, added docs for the `logger` parameter, and directed this pull request towards 5.13. I also added the `logger` parameter to https://github.com/vega/vega/pull/2661.

**Comment by domoritz** [comment]
I rebased the branch and resolved the merge conflict.

**Comment by jheer** [comment]
Um so did I. Looks like my force push landed a few seconds after yours, plus includes fixes.

**Pull request merged**
