### PR TITLE
WIP Custom tick formatting function

### PR DESCRIPTION
**Pull request by curran**
First step proposal towards #608

This is horribly incomplete as a PR I do realize (no tests, have not even verified if it works), but I wanted to put this forth as a proposed direction to move in.

Any thoughts? What would this break? It would be outside the JSON Schema for Vega specs definitely, but maybe that's OK.

Related discussion in https://github.com/vega/vega-lite-api/issues/12

### CODE REVIEW

**Comment by domoritz** [comment]
You can add custom functions with https://vega.github.io/vega/docs/api/extensibility/#expressions. I don't think we necessary need this addition, although it is certainly less cumbersome.

**Comment by curran** [comment]
Expression functions could work!

At the end of the day, what I'd really like to see is a working implementation that formats this original example https://observablehq.com/@mbostock/working-with-wikipedia-data using "$90B" rather than "90G".

**Comment by domoritz** [comment]
I think our discussion in https://github.com/vega/vega-lite/issues/5122 shows that we should go a different route first and see whether it's too limited.

**Comment by curran** [comment]
Sounds good. Thank you for moving this forward!

**Pull request closed without merging**
