### PR TITLE
feat: add axis `labelOffset`

### PR DESCRIPTION
**Pull request by kanitw**
fix https://github.com/vega/vega/issues/2317

Note: I'm not sure if a Vega PR should include generate files in docs, so I'm separating them into another commit that you can easily drop.

### CODE REVIEW

**Comment by domoritz** [comment]
Generally, Vega PRs are not supposed to include compiled files. It's not documented in https://github.com/vega/vega/blob/master/CONTRIBUTING.md, though.

**Comment by kanitw** [comment]
Why are they not in `.npmignore` list then?

**Comment by jheer** [comment]
Thanks! Overall this looks good to me, but I will keep this PR open until we have a v5.10.0 branch started, then re-target it to merge there.

**Comment by kanitw** [comment]
Thanks @jheer -- any timeline for 5.10.0?  

We'd love to include this and aria-label/tabindex PR (https://github.com/vega/vega/pull/2343) in VL soon.

**Pull request merged**
