### PR TITLE
Add links to forkable Vega Block.

### PR DESCRIPTION
**Pull request by domoritz**

### CODE REVIEW

**Comment by domoritz** [comment]
So it's "block" not "Block"? If so, I should change that in the Vega-Lite docs.

**Comment by jheer** [comment]
I don't know if there is a canonical capitalization here. TBH I just went based on how it looked to me...

**Comment by domoritz** [comment]
Looks like Mike uses "Block" (https://bl.ocks.org/-/about).

screen shot 2017-06-05 at 16 31 25

**Comment by jheer** [comment]
I'm convinced! I'll switch it back in my beta.34 branch.

**Pull request merged**
