### PR TITLE
fix: correct aggregate params types

### PR DESCRIPTION
**Pull request by domoritz**
Follow up for https://github.com/vega/vega/pull/3686

### CODE REVIEW

**Comment by julieg18** [comment]
Hello, is there anything blocking this PR from getting merged? Anything we can help with to move this forward?

**Comment by domoritz** [comment]
@lsh can we include this in the next release?

**Comment by lsh** [comment]
@domoritz no complaints from me!

**Comment by domoritz** [comment]
Please approve so we can merge.

**Review by lsh — APPROVED** [review]

**Comment by julieg18** [comment]
Hello, thanks for releasing this fix in `5.27.0`, it has helped me to progress on https://github.com/vega/vega-lite/issues/9200. Would it be possible to update `vega-cli`, setting its required `vega` dependency version to be `5.27.0` instead of `5.26.1`? 

Since `vega-lite` installs `vega` through `vega-cli`, it's installing the version that still contains the types bug, causing the CLI to fail in my PR that adds aggregate params to `vega-lite` (https://github.com/vega/vega-lite/pull/9225)  with:

```
Error: src/compile/data/aggregate.ts(253,7): error TS2322: Type 'number[]' is not assignable to type 'object[]'.
  Type 'number' is not assignable to type 'object'.
```

If there is anything I can do to help, please let me know!

**Comment by domoritz** [comment]
@lsh is working on it.

**Comment by domoritz** [comment]
https://github.com/vega/vega/pull/3862

**Comment by domoritz** [comment]
@lsh made a release and is working on updating the dependency in Vega-Lite.

**Comment by lsh** [comment]
Merged into VL! Thanks for checking about this @julieg18!

**Pull request merged**
