### PR TITLE
Vega 2.0

### PR DESCRIPTION
**Pull request by arvind**
v2 is a ground-up rewrite of Vega with two marquee features: streaming input data, and declarative interaction design. Other features include: a "reactive geometry", a JSON schema to validate Vega specifications, and a new Vega editor w/syntax highlighting, coding folding, etc.

### CODE REVIEW

**Comment by domoritz** [comment]
Wohoo :sparkles:

**Comment by maspwr** [comment]
:fireworks:

**Comment by vlandham** [comment]
:tada: :tada: :tada:

**Comment by domoritz** [comment]
:beers:

**Comment by gerwitz** [comment]
> 19,505 additions and 21,944 deletions.

😲

**Comment by ajturner** [comment]
:rocket:

**Comment by jeffbaumes** [comment]
:+1:

**Pull request merged**
